name: priest_assistant
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.1
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  path_provider: ^2.0.1
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  font_awesome_flutter: ^9.0.0
  flutter_rounded_date_picker: 2.0.2
  email_validator: ^2.0.1
  country_code_picker: ^2.0.2
  image_picker: ^0.8.3+2
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  flutter_slidable: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  build_runner:


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/images/
  fonts:
   - family: Cairo
     fonts:
       - asset: assets/fonts/Cairo-Regular.ttf
       - asset: assets/fonts/Cairo-Light.ttf
       - asset: assets/fonts/Cairo-SemiBold.ttf
       - asset: assets/fonts/Cairo-Black.ttf
       - asset: assets/fonts/Cairo-Bold.ttf
         weight: 700
   - family: Mirza
     fonts:
       - asset: assets/fonts/Mirza-Medium.ttf
       - asset: assets/fonts/Mirza-Regular.ttf
       - asset: assets/fonts/Mirza-SemiBold.ttf
       - asset: assets/fonts/Mirza-Bold.ttf
         weight: 700